name: app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: 0.5.7+3
  http: ^0.12.1
  data_connection_checker: ^0.3.4
  connectivity: ^2.0.2
  carousel_slider: ^3.0.0
  shimmer: ^1.1.2
  flutter_html: ^1.0.0
  top_sheet: ^0.0.4
  syncfusion_flutter_sliders: ^18.4.49-beta
  sqflite: ^1.3.1+1
  fluttertoast: ^4.0.1
  google_maps_flutter: 0.5.28+1
  clippy_flutter: ^1.1.0
  device_info: ^1.0.0
  pin_code_fields: ^4.0.0
  image_picker: ^0.6.7+22
  flutter_image_compress: ^0.7.0
  extended_tabs: ^0.2.3
  package_info: ^0.4.0+17
  photo_view: ^0.10.2
  url_launcher: ^5.4.10
  flutter_inappwebview: ^4.0.0+4
  extended_image: ^0.8.0
  flushbar: ^1.10.4
  # firebase_messaging: 6.0.16
  multi_image_picker2: ^5.0.1
  flutter_absolute_path: ^1.0.6
  flutter_local_notifications: ^1.4.0
  sslcommerz_flutter: ^0.0.3
  flutter_cache_manager: ^2.0.0
  share_plus: ^1.2.0
  percent_indicator: ^1.0.16
  cached_network_image:
  flutter_launcher_icons:
  provider:
  google_fonts:
  permission_handler:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  line_icons: ^1.3.2
  eva_icons_flutter: ^2.0.1
  ionicons: ^0.1.1
  font_awesome_flutter: ^8.12.0

dev_dependencies:
  intl_translation: ^0.17.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_svg: ^0.18.0

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/ios_logo.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - google_fonts/
    - assets/json/
    - lib/localization/languages/bn.json
    - lib/localization/languages/en.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: google_fonts/Roboto-Bold.ttf
          weight: 700
        - asset: google_fonts/Roboto-Medium.ttf
          weight: 500
        - asset: google_fonts/Roboto-Regular.ttf
          weight: 400
        - asset: google_fonts/Roboto-Light.ttf
          weight: 300
        - asset: google_fonts/Roboto-Thin.ttf
          weight: 100
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
