class Images {

  Images._();

  static final String appIcon = "assets/images/logo.png";
  static final String bdFlag = "assets/images/bangladesh.png";
  static final String usaFlag = "assets/images/usa.png";
  static final String filter = "assets/images/filter.png";
  static final String couponIcon = "assets/images/coupon_icon.png";
  static final String address = "assets/images/address.png";
  static final String card = "assets/images/card.png";
  static final String cardWhite = "assets/images/card_white.png";
  static final String confirmation = "assets/images/confirmation.png";
  static final String confirmationWhite = "assets/images/confirmation_white.png";
  static final String userIcon = "assets/images/user_icon.png";
  static final String cash = "assets/images/cash.png";
  static final String onlinePayment = "assets/images/online_payment.png";
  static final String refund = "assets/images/refund.png";
  static final String cart = "assets/images/cart.png";
  static final String category = "assets/images/category.png";
  static final String confusion = "assets/images/confusion.png";
  static final String password = "assets/images/password.png";
  static final String verify = "assets/images/verify.png";
  static final String profile = "assets/images/profile.png";
  static final String shoppingBag = "assets/images/shopping_bag.png";
  static final String changePassword = "assets/images/change_password.png";
  static final String terms = "assets/images/term.png";
  static final String report = "assets/images/report.png";
  static final String information = "assets/images/information.png";
  static final String translate = "assets/images/translate.png";
  static final String logout = "assets/images/logout.png";
  static final String enter = "assets/images/enter.png";
  static final String coupon = "assets/images/coupon.png";
  static final String delivery = "assets/images/delivery.png";
  static final String payment = "assets/images/payment.png";
  static final String info = "assets/images/info.png";
  static final String voucher = "assets/images/voucher.png";
  static final String accept = "assets/images/accept.png";
  static final String descendant = "assets/images/descendant.png";
  static final String messenger = "assets/images/messenger.png";
  static final String whatsapp = "assets/images/whatsapp.png";
  static final String viber = "assets/images/viber.png";
  static final String imo = "assets/images/imo.png";
  static final String telephone = "assets/images/telephone.png";
  static final String email = "assets/images/email.png";
  static final String busTicket = "assets/images/bus_ticket.png";
  static final String launchTicket = "assets/images/launch_ticket.png";
  static final String flightTicket = "assets/images/flight_ticket.png";
  static final String topUp = "assets/images/top_up.png";
  static final String addMoney = "assets/images/add_money.png";
  static final String moneyWithdraw = "assets/images/money_withdraw.png";
  static final String landscapeLogo = "assets/images/landscape_logo.png";
  static final String wishList = "assets/images/wishlist.png";
  static final String privacy = "assets/images/privacy.png";
}